{
 "title": "Trading - JVM services",
 "tags": [ "trading" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Service",
    "query": "jvm_memory_bytes_used{job=~\".+\"}"
   }
  ]
 },
 "panels": [
  { "title": "$job", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "job" },
  {
   "title": "Heap Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(jvm_memory_bytes_committed{job=~\"$job\"})",
     "legendFormat": "Heap size"
    },
    {
     "expr": "avg(jvm_memory_bytes_used{job=~\"$job\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "avg(jvm_memory_bytes_max{job=~\"$job\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(irate(process_cpu_seconds_total{job=~\"$job\"}[60s]) * 100)"
    }
   ]
  },
  {
   "title": "GC Pause",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(increase(jvm_gc_collection_seconds_sum{job=~\"$job\"}[60s]))",
     "legendFormat": "Pause"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "round(avg(jvm_threads_current{job=~\"$job\"}))",
     "legendFormat": "Current"
    },
    {
     "expr": "round(avg(jvm_threads_daemon{job=~\"$job\"}))",
     "legendFormat": "Daemon"
    },
    {
     "expr": "round(avg(jvm_threads_deadlocked {job=~\"$job\"}))",
     "legendFormat": "Deadlock"
    }
   ]
  }
 ]
}