addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"             % "0.4.2")
addSbtPlugin("io.spray"                  % "sbt-revolver"             % "0.9.1")
addSbtPlugin("com.github.sbt"            % "sbt-native-packager"      % "1.9.16")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"             % "2.5.0")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"             % "0.10.4")
addSbtPlugin("org.scala-js"              % "sbt-scalajs"              % "1.13.0")
addSbtPlugin("org.portable-scala"        % "sbt-scalajs-crossproject" % "1.2.0")
addSbtPlugin("com.github.reibitto"       % "sbt-welcome"              % "0.3.1")
