addSbtPlugin("org.typelevel"       % "sbt-tpolecat"             % "0.5.2")
addSbtPlugin("io.spray"            % "sbt-revolver"             % "0.10.0")
addSbtPlugin("com.github.sbt"      % "sbt-native-packager"      % "1.11.1")
addSbtPlugin("org.scalameta"       % "sbt-scalafmt"             % "2.5.4")
addSbtPlugin("ch.epfl.scala"       % "sbt-scalafix"             % "0.13.0")
addSbtPlugin("org.scala-js"        % "sbt-scalajs"              % "1.17.0")
addSbtPlugin("org.portable-scala"  % "sbt-scalajs-crossproject" % "1.3.2")
addSbtPlugin("com.github.reibitto" % "sbt-welcome"              % "0.5.0")
