name: Scala.js

on:
  pull_request:
    branches:
      - main
    paths:
      - 'modules/ws-client/**'
  push:
    branches:
      - main
    paths:
      - 'modules/ws-client/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2.3.2

      - name: "Install Nix ❄️"
        uses: cachix/install-nix-action@v15

      - name: "Install Cachix ❄️"
        uses: cachix/cachix-action@v10
        with:
          name: feda
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: "Build Tyrian (Scala.js) webapp 🚀"
        run: cd modules/ws-client && nix build
